from .tools.fov import web_router
from .tools.partials import web_router
from .gear.cameras import web_router
from .i18n import i18n_middleware
from .index import web_router
from .tools.tools_list import web_router
from .media import media_router
from .gear.compare_lens import web_router
from .gear.comparison_lists import web_router
from .gear.gear_manufacturers import web_router